# Generated by Django 6.0.3 on 2026-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='started at'),
        ),
    ]
