# Generated by Django 6.0.3 on 2026-04-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_country_city'),
        ('courses', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='notification',
            name='category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='notification',
            name='category_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='notification',
            name='course_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='course_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='course_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_uz',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='module_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='notification',
            name='module_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='notification',
            name='module_uz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
